### ISSUE TITLE
Invalid response when body is empty

### ISSUE THREAD

**Issue by Dennor** [Syncano/syncano-node#55] opened 2017-12-06 13:19 UTC
### Expected behaviour

```
HTTP/1.1 200 OK
Server: nginx
Content-Type: text/plain; charset=utf-8
Content-Length: 122
Connection: keep-alive
Keep-Alive: timeout=20
Date: Wed, 06 Dec 2017 13:13:17 GMT
```

When response is returned and is empty, it should stay empty.

### Actual behaviour

```
HTTP/1.1 200 OK
Server: nginx
Content-Type: text/plain; charset=utf-8
Content-Length: 122
Connection: keep-alive
Keep-Alive: timeout=20
Date: Wed, 06 Dec 2017 13:13:17 GMT

{"id":27,"executed_at":"2017-12-06T13:13:17.344436Z","status":"success","duration":810,"result":{"stdout":"","stderr":""}}
```

#### socket.yml
```yaml
name: fail-case
description: Description of fail-case
version: 0.0.1

endpoints:
  fail-case:
    file: fail-case.js
    description: Empty response
    parameters:
    response:
```

#### src/fail-case.js

```javascript
import Server from 'syncano-server';

export default async ctx => {
  const {response} = Server(ctx);
  return response('', 200, 'text/plain', {});
};
```

#### package.json
```json
{
  "license": "MIT",
  "dependencies": {
    "syncano-server": "beta"
  },
  "devDependencies": {
    "eslint": "^4.12.1"
  }
}
```

#### npx s version
```
0.53.0
```
When script returns an empty response, it replaces it with script execution info. Sometimes empty response is an expected behaviour. It can be useful for application/octet-stream and text/plain content-type responses, but it also fails at empty application/json.

**Comment by 23doors** [comment] 2017-12-06 13:47
Hey @Dennor! It seems that here the issue is not with the response being empty but with returning it from a Promise. This should work without `async` keyword. If you need `async` here - we should be able to add support for exporting async functions in a few days.

**Comment by Dennor** [comment] 2017-12-06 14:07
```
import Server from 'syncano-server';

export default async ctx => {
  const {response} = Server(ctx);
  return response('text', 200, 'text/plain', {});
};
```

With code like this, the response I'm getting is:
```
HTTP/1.1 200 OK
Server: nginx
Content-Type: text/plain; charset=utf-8
Content-Length: 4
Connection: keep-alive
Keep-Alive: timeout=20
Date: Wed, 06 Dec 2017 14:05:25 GMT

text
```

I'm using syncano-cli by the way, so async get's transpilled away.

**Comment by 23doors** [comment] 2017-12-06 14:09
As I mentioned in above comment - `async` here is the issue. Transpiled or not - async in export is not fully handled in terms of return response.

**Comment by Dennor** [comment] 2017-12-06 14:14
```
import Server from 'syncano-server';

export default ctx => {
  const {response} = Server(ctx);
  return response('', 200, 'text/plain', {});
};
```

Still getting:
```
HTTP/1.1 200 OK
Server: nginx
Content-Type: text/plain; charset=utf-8
Content-Length: 120
Connection: keep-alive
Keep-Alive: timeout=20
Date: Wed, 06 Dec 2017 14:10:45 GMT

{"id":51,"executed_at":"2017-12-06T14:10:45.141419Z","status":"success","duration":4,"result":{"stdout":"","stderr":""}}
```

As I've said, **every** other response, except for response with empty body, as in,
```
return response('', 200, 'application/json', {});
return response('', 200, 'application/octet-stream', {});
return response('', 200, 'text/plain', {});
```
Is returning, what it's supposed to be returning, when the body is empty I'm getting execution context state. Tested just now with both, with and withou async keyword.

**Comment by 23doors** [comment] 2017-12-06 15:02
You are right. Turns out that both handling `async` in backend part and incorrectly checking `content` are an issue here.

**Comment by Idered** [comment] 2017-12-20 10:39
@Dennor @23doors I've removed content check as suggested in https://github.com/Syncano/syncano-server-js/issues/99 . It will now always call underneath setResponse. I guess that resolves this issue. Right @Dennor ?

**Comment by mkucharz** [comment] 2018-01-24 21:41
@Dennor @23doors are we good here?

**Comment by mkucharz** [comment] 2018-01-30 21:46
@Dennor @23doors @Idered closing.

**Closed by mkucharz** 2018-01-30 21:46 UTC
Labels: BUG, CORE, PLATFORM
